# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea076bf79bfc608877dbcdbbc68a46c1194e88e7efdeb0da674e71ac7afe453f283030257ed14d0a5c4264f583afafda880fb599fda4d00f2f369792a27cf5b8

test:
  secret_key_base: 8977a73ab1d3676895b1d53eb8297cfe558c01723b1f9f08cab128827717e50dc9560248474ffb5695c1a1c4a39c8c8060924f01de8cbffbdaac6cd5ed626921

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
